### ISSUE TITLE
Action no longer downloads the installer, it only downloads the webpage

### ISSUE THREAD

**Issue by nerudaj** [repolevedavaj/install-nsis#19]
Exactly what the title says, you can easily reproduce by running the commands manually on your machine:

```
Invoke-WebRequest https://netcologne.dl.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08-setup.exe -OutFile C:\WINDOWS\Temp\nsis-3.08-setup.exe
& C:\WINDOWS\Temp\nsis-3.08-setup.exe \S
```

and you will get:
![image](https://github.com/user-attachments/assets/3136f3b7-c8eb-4d84-bd84-22d46ef7dcc3)

The file should be 1.48MB, instead it has 114kB and contains the Sourceforge html code:

![image](https://github.com/user-attachments/assets/8ccadc57-7ff6-42b5-bd47-6fa4300129b7)

I encountered this issue today and last succesful run of my CI was three days ago, so SF must've changed something in those three days.

**Comment by repolevedavaj** [comment]
I just released a new version with the new URL: https://github.com/repolevedavaj/install-nsis/releases/tag/v1.0.2
Lets hope that the URL keeps stable for some time.

**Comment by nerudaj** [comment]
Wow, that was quick, kudos!
