### ISSUE TITLE
had to use '3.10' in version, instead of just 3.10, otherwise, it was truncated to 3.1

### ISSUE THREAD

**Issue by Skall34** [repolevedavaj/install-nsis#21]
Hi.

Not a big deal, since I found a workaround, but to use nsis 3.10, I had to put the version number between '', otherwise,
it was truncated to 3.1.

Just for your information.

**Comment by repolevedavaj** [comment]
Thanks for the hint, I updated the readme with the version 3.10 to have an example using ''
